---{% set hosts = [LMS_HOST, "preview." + LMS_HOST, CMS_HOST] %}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
  labels:
    app.kubernetes.io/name: web
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1000m
    rancher.io/globalDNS.hostname: {{LMS_HOST}}
    {% if ACTIVATE_HTTPS%}{{ISSUER_CLASS}}: {{DEFAULT_ISSUER}}
    {% endif %}
spec:
  rules:
  {% for host in hosts %}
  - host: {{ host }}
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: {% if ACTIVATE_HTTPS %}443{% else %}80{% endif %}{% endfor %}
  {{ patch("k8s-ingress-rules")|indent(2) }}
  {% if ACTIVATE_HTTPS %}
  tls:
  - hosts:
    {% for host in hosts %}
    - {{ host }}{% endfor %}
    {{ patch("k8s-ingress-tls-hosts")|indent(6) }}
    secretName: academy-tls
  {%endif%}
