{% if ACTIVATE_ELASTICSEARCH %}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch
  labels:
    app.kubernetes.io/component: volume
    app.kubernetes.io/name: elasticearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
{% endif %}
{% if ACTIVATE_MONGODB %}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: volume
    app.kubernetes.io/name: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{% endif %}
{% if ACTIVATE_MYSQL %}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  labels:
    app.kubernetes.io/component: volume
    app.kubernetes.io/name: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{% endif %}
{% if ACTIVATE_RABBITMQ %}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/component: volume
    app.kubernetes.io/name: rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{% endif %}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  labels:
    app.kubernetes.io/component: volume
    app.kubernetes.io/name: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
{{ patch("k8s-volumes") }}