
steps:
- task: TriggerBuild@3
  inputs:
    definitionIsInCurrentTeamProject: true
    buildDefinition: 'dev/*'
    queueBuildForUserThatTriggeredBuild: true
    ignoreSslCertificateErrors: false
    useSameSourceVersion: true
    useSameBranch: true
    waitForQueuedBuildsToFinish: false
    storeInEnvironmentVariable: true
    authenticationMethod: 'Personal Access Token'
    enableBuildInQueueCondition: false
    dependentOnSuccessfulBuildCondition: false
    dependentOnFailedBuildCondition: false
    checkbuildsoncurrentbranch: false
    failTaskIfConditionsAreNotFulfilled: false

# build tutor
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6.9'
    addToPath: true
    architecture: 'x64'


- script: |
    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
    pip3 install -e .

  displayName: 'pip tutor'

- task: PublishPipelineArtifact@1
  inputs:
    path: $(Build.SourcesDirectory)
    artifact: tutor
