# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: k8s

steps:

- script: |
    mkdir -p $HOME/.kube/
    echo $KUBECONFIG > $HOME/.kube/config
  displayName: 'Create directory for tutor config file and kube config'

- script: |
    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
    apt install python3 libyaml-dev python3-pip
    pip3 install --ignore-installed wheel
    pip3 install -e .
    curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    chmod +x ./kubectl
    mv -n ./kubectl /usr/local/bin/kubectl
    
  displayName: 'Install tutor'

- task: CmdLine@2
  continueOnError: true
  inputs:
    script: |
      printf 'kh.academy\nstudio.kh.academy\nKH Academy\nacademy@arfront.com\n\nn\n' | tutor k8s quickstart
      

- task: CmdLine@2
  inputs:
    script: |
      export LC_ALL=C.UTF-8
      export LANG=C.UTF-8
      tutor k8s start