# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev/*

pool: k8s

steps:

- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'

- task: DownloadSecureFile@1
  name: kubeconfig
  inputs:
    secureFile: 'dev-kubeconfig'

- script: |
    echo Injecting kubeconfig...
    mkdir -p $HOME/.kube/
    cp -r $(kubeconfig.secureFilePath) $HOME/.kube/config
    rm $(kubeconfig.secureFilePath)

- script: |
    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
    apt install python3 libyaml-dev python3-pip
    pip3 install --ignore-installed wheel
    pip3 install -e .
    
  displayName: 'Install tutor'
      

- task: CmdLine@2
  inputs:
    script: |
      export LC_ALL=C.UTF-8
      export LANG=C.UTF-8
      tutor k8s stop
      tutor k8s start
